export const RU = {
  news: {
    businessWorldNews: 'Новости делового мира'
  },
  loginOrRegister: {
    registerTitle: 'Зарегистрируйтесь, чтобы продолжить',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    loginCompleteBtlLabel: 'Вход',
    changeOnRegistration: 'Создать аккаунт',
    regStart: 'Зарегистрироваться',
  },
  miscString: {
    password: 'Пароль',
    userName: 'Имя пользователя',
    email: 'Email',
    or: 'или',
  },
  header: {
    home: 'Главная',
    franchises: 'Франшизы',
    readyMadeBusiness: 'Готовый бизнес',
    buyingThroughAGuarantor: 'Покупка через гарант',
    consulting: 'Консалтинг',
    packingFranchises: 'Упаковка франшиз',

    search: 'Поиск',
    sell: 'Продать',
    myTrades: 'Мои сделки',
    favorite: 'Избранное',
    notifications: 'Уведомления',
    account: 'Аккаунт',
    registration: 'Регистрация',
    logIn: 'Вход',
    logOut: 'Выход',
  },
  cabinet_links: {
    sell: 'Продать',
    myDeals: 'Мои сделки',
    favorites: 'Избранное',
    notifications: 'Уведомления',
    logIn: 'Войти',
    account: 'Аккаунт'
  },
  promoBlockCard: {
    recentlyPurchased: 'Недавно приобрели',
    bannerTitle: 'Покупка бизнеса с гарантиями',
  },
  main_page: {
    businessWithGuarantees: 'Вы можете приобрести бизнес с гарантиями',
    quickSearch: 'Быстрый поиск',
    typeOfBusiness: 'Вид бизнеса',
    category: 'Категория',
    city: 'Город',
    price: 'Стоимость',
    onlineDeal: 'Сделка онлайн',
    showMore: 'Показать ещё',
    popularFranchises: 'Популярные франшизы',
    businessBlog: 'Бизнес блог',
    read5minutes : 'читать ~5 минут',
    published: 'опубликовано',
    moreArticles: 'Больше статей',
    ourBlog: 'Перейдите в наш блог и найдите там массу полезной информации.',
    businessCategories: 'Категории бизнеса',
    allReadyMadeBusiness: 'Весь готовый бизнес',
    categoriesOfFranchises: 'Категории франшиз',
    allFranchises: 'Все франшизы'
  },
  primaNgStrings: {
    startsWith: "Начинается с",
    contains: "Содержит",
    notContains: "Не содержит",
    endsWith: "Заканчивается на",
    equals: "равно",
    notEquals: "Не равно",
    noFilter: "Без фильтра",
    lt: "Меньше чем",
    lte: "Меньше или равно",
    gt: "Больше чем",
    gte: "Больше или равно",
    is: "Есть",
    isNot: "Не является",
    before: "До",
    after: "После",
    dateIs: "Дата",
    dateIsNot: "Дата не указана",
    dateBefore: "Дата раньше",
    dateAfter: "Дата после",
    clear: "Очистить",
    apply: "Применить",
    matchAll: "Сопоставить все",
    matchAny: "Соответствует любому",
    addRule: "Добавить правило",
    removeRule: "Удалить правило",
    accept: "Да",
    reject: "Нет",
    choose: "Выбрать",
    upload: "Загрузить",
    cancel: "Отмена",
    dayNames: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
    dayNamesShort: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
    dayNamesMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
    monthNames: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", " Декабрь"],
    monthNamesShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июль", "Авг", "Сент", "Окт", "Ноя", " дек"],
    firstDayOfWeek: 1,
    today: "Сегодня",
    weekHeader: "Неделя",
    weak: "Слабый",
    medium: "Cредний",
    strong: "Сильный",
    passwordPrompt: "Введите пароль",
    emptyMessage: "Результатов не найдено",
    emptyFilterMessage: "Результатов не найдено"
  },
  headerLanding: {
    consulting: {
      title: 'Консультация',
      sublitle: 'по покупке бизнеса и франшиз',
      content_text: 'с сопровождением сделки и составлением договоров',
      content__button: 'Получить консультацию',
      content__button1: 'Консультация',
      alt: 'Изображение блокнота, ручки и портфеля',
    },
    deal: {
      title: 'Онлайн сделка',
      sublitle: 'по покупке бизнеса',
      content_text: 'или франшизы',
      content__button: 'Как начать сделку?',
      alt: 'Изображение щита',
    },
    frachise: {
      title: 'Создание',
      sublitle: 'и упаковка франшиз',
      content_text: 'с бесплатным размещением в каталоге',
      content__button: 'Бесплатная консультация',
      alt: 'Изображение стола, монеты и %',
      alt1: 'Изображение стола, монеты и %',
    }
  }

}
