export const ENG = {
  news: {
    businessWorldNews: 'Business News'
  },
  loginOrRegister: {
    registerTitle: 'Register to continue',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    loginCompleteBtlLabel: 'Login',
    changeOnRegistration: 'Create Account',
    regStart: 'Register',
  },
  miscString: {
    password: 'Password',
    userName: 'Username',
    email: 'Email',
    or: 'or',
  },
  header: {
    home: 'Home Page',
    franchises: 'Franchises',
    readyMadeBusiness: 'Ready-made business',
    buyingThroughAGuarantor: 'Buying through a guarantor',
    consulting: 'Сonsulting',
    packingFranchises: 'Packaging franchises',

    search: 'Search',
    sell: 'Sell',
    myTrades: 'My trades',
    favorite: 'Favorite',
    notifications: 'Notifications',
    account: 'Account',
    registration: 'Registration',
    logIn: 'LogIn',
    logOut: 'LogOut',
  },
  cabinet_links: {
    sell: 'Sell',
    myDeals: 'My deals',
    favorites: 'Favorites',
    notifications: 'Notifications',
    logIn: 'Log in',
    account: 'Account'
  },
  promoBlockCard: {
    sliderTitle: 'Recently purchased',
    bannerTitle: 'Purchase of business with guarantees',
  },
  main_page: {
    businessWithGuarantees: 'You can buy a business with guarantees',
    quickSearch: 'Quick search',
    typeOfBusiness: 'Type of business',
    category: 'Category',
    city: 'City',
    price: 'Price',
    onlineDeal: 'Online Deal',
    showMore: 'Show more',
    popularFranchises: 'Popular franchises',
    businessBlog: 'Business Blog',
    read5minutes: 'read ~5 minutes',
    published: 'published',
    moreArticles: 'More articles',
    ourBlog: 'Go to our blog and you will find a lot of useful information there.',
    businessCategories: 'Business categories',
    allReadyMadeBusiness: 'All ready-made business',
    categoriesOfFranchises: 'Categories of franchises',
    allFranchises: 'All franchises'
  },
  primaNgStrings: {
    startsWith: "Starts with",
    contains: "Contains",
    notContains: "Not contains",
    endsWith: "Ends with",
    equals: "Equals",
    notEquals: "Not equals",
    noFilter: "No Filter",
    lt: "Less than",
    lte: "Less than or equal to",
    gt: "Greater than",
    gte: "Greater than or equal to",
    is: "Is",
    isNot: "Is not",
    before: "Before",
    after: "After",
    dateIs: "Date is",
    dateIsNot: "Date is not",
    dateBefore: "Date is before",
    dateAfter: "Date is after",
    clear: "Clear",
    apply: "Apply",
    matchAll: "Match All",
    matchAny: "Match Any",
    addRule: "Add Rule",
    removeRule: "Remove Rule",
    accept: "Yes",
    reject: "No",
    choose: "Choose",
    upload: "Upload",
    cancel: "Cancel",
    dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    dayNamesMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    monthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    monthNamesShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    dateFormat: "mm/dd/yy",
    firstDayOfWeek: 0,
    today: "Today",
    weekHeader: "Wk",
    weak: "Weak",
    medium: "Medium",
    strong: "Strong",
    passwordPrompt: "Enter a password",
    emptyMessage: "No results found",
    emptyFilterMessage: "No results found"
  }
}
