export const BLR = {
  news: {
    businessWorldNews: 'Навіны дзелавога свету'
  },
  loginOrRegister: {
    registerTitle: 'Зарэгіструйцеся, каб працягнуць',
    rememberMe: 'Запомніць мяне',
    forgotPassword: 'Забыліся пароль?',
    loginCompleteBtlLabel: 'Уваход',
    changeOnRegistration: 'Стварыць рахунак',
    regStart: 'зарэгістравацца',
  },
  miscString: {
    password: 'Пароль',
    userName: 'імя карыстальніка',
    email: 'Email',
    or: 'ці',
  },
  header: {
    home: 'Галоўная',
    franchises: 'Франшызы',
    readyMadeBusiness: 'Гатовы бізнес',
    buyingThroughAGuarantor: 'Купля праз гарант',
    consulting: 'Кансалтынг',
    packingFranchises: 'Упакоўка франшыз',

    search: 'Пошук',
    sell: 'Прадаць',
    myTrades: 'Мае здзелкі',
    favorite: 'Абранае',
    notifications: 'Паведамленні',
    account: 'Рахунак',
    registration: 'Рэгістрацыя',
    logIn: 'Уваход',
    logOut: 'Выхад',
  },
  cabinet_links: {
    sell: 'Прадаць',
    myDeals: 'Мае здзелкі',
    favorites: 'Абранае',
    notifications: 'Паведамленні',
    logIn: 'Увайсці',
    account: 'Рахунак'
  },
  promoBlockCard: {
    recentlyPurchased: 'Нядаўна набылі',
    bannerTitle: 'Купля бізнесу з гарантыямі',
  },
  main_page: {
    businessWithGuarantees: 'Вы можаце набыць бізнес з гарантыямі',
    quickSearch: 'Хуткі пошук',
    typeOfBusiness: 'Від бізнесу',
    category: 'Катэгорыя',
    city: 'Горад',
    price: 'Кошт',
    onlineDeal: 'Здзелка онлайн',
    showMore: 'Паказаць яшчэ',
    popularFranchises: 'Папулярныя франшызы',
    businessBlog: 'Бізнес блог',
    read5minutes: 'чытаць ~5 хвілін',
    published: 'апублікаваны',
    moreArticles: 'Больш артыкулаў',
    ourBlog: 'Перайдзіце ў наш блог ды знайдзіце там шмат карыснай інфармацыі.',
    businessCategories: 'Катэгорыі бізнесу',
    allReadyMadeBusiness: 'Увесь гатовы бізнес',
    categoriesOfFranchises: 'Катэгорыі франшыз',
    allFranchises: 'Усе франшызы'
  },
  primaNgStrings: {
    startsWith: "Пачынаецца з",
    contains: "Змяшчае",
    notContains: "Не ўтрымлівае",
    endsWith: "Заканчваецца на",
    equals: "Роўна",
    notEquals: "Не роўна",
    noFilter: "Без фільтра",
    lt: "Менш чым",
    lte: "Менш або роўна",
    gt: "Больш чым",
    gte: "Больш або роўна",
    is: "Ёсць",
    isNot: "Не з'яўляецца",
    before: "Да",
    after: "Пасля",
    dateIs: "Дата",
    dateIsNot: "Дата не пазначана",
    dateBefore: "Дата раней",
    dateAfter: "Дата пасля",
    clear: "Ачысціць",
    apply: "Прымяніць",
    matchAll: "Супаставіць усё",
    matchAny: "Адпавядае любому",
    addRule: "Дадаць правіла",
    removeRule: "Выдаліць правіла",
    accept: "Так",
    reject: "Не",
    choose: "Выбраць",
    upload: "Загрузіць",
    cancel: "Адмена",
    dayNames: ["Нядзеля", "Панядзелак", "Аўторак", "Серада", "Чацвер", "Пятніца", "Субота"],
    dayNamesShort: ["Нядз", "Пн", "Аўт", "Сер", "Чац", "Пт", "Сб"],
    dayNamesMin: ["Нядз", "Пн", "Аўт", "Сер", "Чац", "Пт", "Сб"],
    monthNames: ["Студзень", "Люты", "Сакавік", "Красавік", "Май", "Чэрвень", "Ліпень", "Жнівень", "Верасень", "Кастрычнік", "Лістапад", " Снежань"],
    monthNamesShort: ["Студ", "Люты", "Сак", "Крас", "Май", "Чэрв", "Ліп", "Жнів", "Верас", "Кастр", "Ліст", " Снеж"],
    firstDayOfWeek: 1,
    today: "Сёння",
    weekHeader: "Нядзеля",
    weak: "Слабы",
    medium: "Cярэдні",
    strong: "Моцны",
    passwordPrompt: "Увядзіце пароль",
    emptyMessage: "Вынікаў не знойдзена",
    emptyFilterMessage: "Вынікаў не знойдзена"
  },
  headerLanding: {
    consulting: {
      title: 'кансультацыя',
      subtitle: 'па куплі бізнесу і франшызы',
      content_text: ' з суправаджэннем здзелкі і складаннем дагавораў',
      content__button: 'атрымаць кансультацыю',
      content__button1: 'кансультацыя',
      alt: 'Малюнак нататніка, ручкі і партфеля',
    },
    deal: {
      title: 'Анлайн здзелка',
      subtitle: 'па куплі бізнесу',
      content_text: 'або франшызы',
      content__button: 'як пачаць здзелку?',
      alt: 'Выява шчыта',
    },
    franchise: {
      title: 'Стварэнне',
      subtitles: 'і ўпакоўка франшызы',
      content_text: 'з бясплатным размяшчэннем у каталогу',
      content__button: 'Бясплатная кансультацыя',
      alt: 'Выява стала, манеты і %',
      alt1: 'выява стала, манеты і %',
    }
  }

}
